# TODO
# what about sizing these VMs for performance?
# do I want my own telegraf VM that has all the MIBs included?
# where should I get the MIBs? Juniper?
# Add more MIBs from other providers
# where/how do we want to be persisting data
# it's host networking, which telegraf requires, at least to connect to the VMs on the same host
# how to get this to startup on device boot
# do I want kubernetes anywhere

version: "3"
services:
  prometheus:
    container_name: mfn_prometheus
    image: prom/prometheus
    network_mode: "host"
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  grafana:
    container_name: mfn_grafana
    image: grafana/grafana
    network_mode: "host"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yml
    restart: always

  telegraf:
    container_name: mfn_telegraf
    image: telegraf
    network_mode: "host"
    ports:
      - "9012:9012"
    environment:
      - MIBDIRS=/usr/share/snmp/mibs:/usr/share/snmp/mibs/StandardMibs:/usr/share/snmp/mibs/JuniperMibs
      - MIBS=ALL
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mibs/StandardMibs:/usr/share/snmp/mibs/StandardMibs:ro
      - ./mibs/JuniperMibs:/usr/share/snmp/mibs/JuniperMibs:ro
    restart: always

